# -*- coding: utf-8 -*-
"""Week 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/141x5-cxjcX4nxDqnpJjQ7gHHKX5QchcK

반복문
"""

for i in range(5) :
  print(i)

for i in range(1,5,1) :
  print(i, end=" ")

i=0
sum=0
for i in range(1,11,1) :
  sum=sum+i
print("1에서 10까지 자연수의 합 : %d" %sum)

sum=0
for num in range(5) :
  num=int(input("어떤 수 : "))
  if num%2==1 :
    print(f"{num}은(는) 홀수입니다.")
    sum+=1
  else :
    print(f"{num}은(는) 짝수입니다.")
  
print(f"\n홀수 개수 : {sum}")

"""for문과 리스트"""

num=[1,2,3,4,5]
for i in num :
  print(i)

alpha=["a","b","c","d","e"]
for i in alpha[::-1] :
  print(i)

alpha=["a","b","c","d","e"]
alpha.reverse()
for i in alpha :
  print(i)

zoo=["rabbit", "goat", "tiger", "lion", "giraffe", "zebra"]
zoo.reverse()
for i in zoo :
  print(i, end=" ")

zoo=["rabbit", "goat", "tiger", "lion", "giraffe", "zebra"]
zoo.reverse()
for animal in zoo :
  print(animal,":",len(animal))

zoo=["rabbit", "goat", "tiger", "lion", "giraffe", "zebra"]
fav=input("내가 좋아하는 동물?")
if fav in zoo :
  print(f"{fav}은(는) 동물원에 있습니다.")
else :
  print(f"{fav}은(는) 동물원에 없습니다.")

"""while 반복문"""

cnt=0
while cnt<5 :
  cnt+=1
  print(cnt)

i=0
while True:
  i+=1
  print(i)

for i in range(1,6):
  print(f"Python Program {i}번 출력")

i=1
while i < 6 :
  print(f"Python Program {i}번 출력")
  i+=1

num=int(input("원하는 구구단 : "))
i=0
while i<9 :
  i+=1
  print(f"{num}*{i}={num*i}")

"""**수행평가**"""

animal=["dog","duck","pony","donkey","giraffe","elephant","cat"]
for i in animal :
  if len(i)<5 :
    print(i)