# -*- coding: utf-8 -*-
"""Week 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VYPBkuz7B4h7sRkdxQC-V1BWdtrkcL2j

if ~ else 조건문
"""

설계=int(input("소프트웨어 설계 : "))
개발=int(input("소프트웨어 개발 : "))
구축=int(input("데이터베이스 구축 : "))
활용=int(input("프로그래밍 언어 활용 : "))
관리=int(input("정보시스템 구축 관리 : "))
평균=int((설계+개발+구축+활용+관리)/5)
print("평균:", 평균)
if 설계>=40 and 개발>=40 and 구축>=40 and 활용>=40 and 관리>=40 and 평균>=60 :
  print("결과 : 합격")
else :
  print("결과 : 불합격")

"""중첩 if 문"""

num=int(input("어떤 수? "))
if num>=100 :
  print(f"입력한 수 {num}은 100보다 큽니다.")
else :
  if num>50 :
    print(f"입력한 수 {num}은 50보다 크고 100보다 작습니다.")
  else :
    print(f"입력한 수 {num}은 50보다 작습니다.")

"""if ~ elif ~ else 문"""

num=int(input("어떤 수? "))
if num//1000>0 :
  print("네 자릿수 숫자입니다.")
elif num//100>0:
  print("세 자릿수 숫자입니다.")
elif num//10>0 :
  print("두 자릿수 숫자입니다.")
else :
  print("한 자릿수 숫자입니다.")

num=int(input("어떤 수? "))
if num in range(1, 10) :
  print("한 자릿수 숫자입니다.")
elif num in range(10, 100) :
  print("두 자릿수 숫자입니다.")
elif num in range(100,1000) :
  print("세 자릿수 숫자입니다.")
elif num in range(1000,10000) :
  print("네 자릿수 숫자입니다.")

num=(input("어떤 수? "))
if len(num) == 4 :
  print("네 자릿수 숫자입니다.")
elif len(num) == 3 :
  print("세 자릿수 숫자입니다.")
elif len(num) == 2 :
  print("두 자릿수 숫자입니다.")
else :
  print("한 자릿수 숫자입니다.")

"""if 조건과 list"""

fruit=["딸기", "포도", "망고", "복숭아", "수박"]
choose = input("과일을 입력하세요 : ")
if choose in fruit :
  print(f"맛있는 {choose}가 있습니다.")
else :
  print(f"{choose}가 없습니다.")

"""*비교할 땐 항상 == 두번써야됨*"""

코드=["1203", "1250", "1275", "1290"]
code = input("교수 교과목 코드 : ")
if code in 코드 :
  if code=="1203" :
    print("과목명 : 파이썬 프로그래밍")
  elif code=="1250" :
    print("과목명 : 컴퓨팅 사고")
  elif code=="1275" :
    print("과목명 : 빅 데이터")
  else :
    print("과목명 : IoT")
else :
  print("해당 강좌 없음")

"""**수행평가**"""





"""**문제 1**"""

weight=float(input())
if weight<=50.80 :
  print("Flyweight")
elif weight<=61.23 :
  print("Lightweight")
elif weight<=72.57 :
  print("Middletweight")
elif weight<=88.45 :
  print("Cruisertweight")
else :
  print("Heavyweight")

"""**문제 2**"""

month=input()
long=["1", "3", "5", "7", "8", "10", "12"]
middle=["4","6", "9", "11"]
short=["2"]
if month in long :
  print("31")
elif month in middle :
  print("30")
elif month in short :
  print("28")
else :
  print("1~12 사이의 정수를 입력하세요.")

"""**문제 3**"""

a, b, c, d, e, f, g, h, i, j = map(int, input().split())
count_dict = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0}
roll = [a, b, c, d, e, f, g, h, i, j]
for num in roll:
    count_dict[num] += 1
for num, count in count_dict.items():
    print(f"{num}: {count}")

a, b, c, d, e, f, g, h, i, j = map(int, input().split())
dice=[1,2,3,4,5,6]
num=[0,0,0,0,0,0]

if a==1 :
  num[0]+=1
elif a==2 :
  num[1]+=1
elif a==3 :
  num[2]+=1
elif a==4 :
  num[3]+=1
elif a==5 :
  num[4]+=1
else :
  num[5]+=1

if b==1 :
  num[0]+=1
elif b==2 :
  num[1]+=1
elif b==3 :
  num[2]+=1
elif b==4 :
  num[3]+=1
elif b==5 :
  num[4]+=1
else :
  num[5]+=1

if c==1 :
  num[0]+=1
elif c==2 :
  num[1]+=1
elif c==3 :
  num[2]+=1
elif c==4 :
  num[3]+=1
elif c==5 :
  num[4]+=1
else :
  num[5]+=1

if d==1 :
  num[0]+=1
elif d==2 :
  num[1]+=1
elif d==3 :
  num[2]+=1
elif d==4 :
  num[3]+=1
elif d==5 :
  num[4]+=1
else :
  num[5]+=1

if e==1 :
  num[0]+=1
elif e==2 :
  num[1]+=1
elif e==3 :
  num[2]+=1
elif e==4 :
  num[3]+=1
elif e==5 :
  num[4]+=1
else :
  num[5]+=1

if f==1 :
  num[0]+=1
elif f==2 :
  num[1]+=1
elif f==3 :
  num[2]+=1
elif f==4 :
  num[3]+=1
elif f==5 :
  num[4]+=1
else :
  num[5]+=1

if g==1 :
  num[0]+=1
elif g==2 :
  num[1]+=1
elif g==3 :
  num[2]+=1
elif g==4 :
  num[3]+=1
elif g==5 :
  num[4]+=1
else :
  num[5]+=1

if h==1 :
  num[0]+=1
elif h==2 :
  num[1]+=1
elif h==3 :
  num[2]+=1
elif h==4 :
  num[3]+=1
elif h==5 :
  num[4]+=1
else :
  num[5]+=1

if i==1 :
  num[0]+=1
elif i==2 :
  num[1]+=1
elif i==3 :
  num[2]+=1
elif i==4 :
  num[3]+=1
elif i==5 :
  num[4]+=1
else :
  num[5]+=1

if j==1 :
  num[0]+=1
elif j==2 :
  num[1]+=1
elif j==3 :
  num[2]+=1
elif j==4 :
  num[3]+=1
elif j==5 :
  num[4]+=1
else :
  num[5]+=1

print("1 :",num[0])
print("2 :",num[1])
print("3 :",num[2])
print("4 :",num[3])
print("5 :",num[4])
print("6 :",num[5])