# -*- coding: utf-8 -*-
"""백준 1단계 입출력과 사칙연산

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lIclCaWHFyVGBKidDD2aR7Ik4ykdhK-T
"""

print("Hello World!")

a, b= map(int, input().split())
print(a+b)

a, b= map(int, input().split())
print(a-b)

a, b= map(int, input().split())
print(a*b)

a, b= map(int, input().split())
print(a/b)

a, b= map(int, input().split())
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a%b)

a=input("")
print(a+"??!")

a=int(input(""))
print(a-543)

A, B, C= map(int, input().split())
print((A+B)%C)
print(((A%C)+(B%C))%C)
print((A*B)%C)
print((((A%C)*(B%C)))%C)

a, b= map(int, input().split())
print(a*(b%10))
print(a*(b%100-c)/10)
print(a*(b-d*10-c)/100)
print(a*b)

a, b= map(int, input().split())
c=b%10
d=(b%100-c)/10
e=(b-d*10-c)/100
print(a*c)
print(a*d)
print(a*e)
print(a*b)

"""-> 런타임에러

=> 리스트 사용

int(num2[2])
"""

num1=int(input(""))
num2=input()
print(num1*int(num2[2]))
print(num1*int(num2[1]))
print(num1*int(num2[0]))
print(num1*int(num2))

a, b, c= map(int, input().split())
print(a+b+c)

print("|\\_/|")
print("|q p|   /}")
print("( 0 )\"\"\"\\")
print("|\"^\"`    |")
print("||_/=\\\\__|")

print("\\    /\\")
print(" )  ( ')")
print("(  /  )")
print(" \\(__)|")