# -*- coding: utf-8 -*-
"""백준 2단계 조건문

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17e9yAgeIYPSBFfXlDOX99qG6LVLWyStG
"""

A, B = map(int, input() .split())
print(">") if A>B else print("<") if A<B else print("==")

score=int(input())
print("A") if 90<=score<=100 else print("B") if 80<=score<=89 else print("C") if 70<=score<=79 else print("D") if 60<=score<=69 else print("F")

year=int(input())
print("1") if year%4==0 and year%100!=0 else print("1") if year%400==0 else print("0")

x=int(input())
y=int(input())
print(1) if x>0 and y>0 else print(2) if x<0 and y>0 else print(3) if x<0 and y<0 else print(4)

H, M = map(int, input() .split())
print(H, M-45) if H>=0 and M>=45 else print(H-1, M+15) if H>0 and M<45 else print(H+23, M+15)

A, B = map(int, input() .split())
C = int(input())
print(A+(B+C)//60, (B+C)%60) if A+(B+C)//60<=23 and (B+C) else print(A+(B+C)//60-24, (B+C)%60)

A, B, C = map(int, input() .split())
max=A if A>B else B
max=C if C>max else max
if A==B==C :
  print(10000+A*1000)
elif A==B or B==C or A==C :
  if A==B or B==C :
    print(1000+B*100)
  else :
    print(1000+C*100)
else :
  print(max*100)