# -*- coding: utf-8 -*-
"""Week 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FTSpSaKO3Zca0wj21ALVj0ZtmWXqDvRM
"""

print("Hello")

print("Hello World")

print("Python Program is Great Program!")

print("안녕 "*10)

print(10, "age")

print(1+1)

print("10+20")

print("10+              20=            ",10+        20)

print("50+50의 합 =", 50+50)

"""sep"""

print("10+20","=", 10+20, sep="@")

"""end"""

print("10+20=", end=">>")
print(10+20)

name="yerin"
print("My name is", name)

"""variable"""

name="정예린"
kibon=20000000
bonus=5000000
salary=kibon+bonus
print("{0}씨 월급은 기본급 {1:,} 보너스 {2:,} 총급여액 {3:,}이다." .format(name,kibon,bonus,salary))

num1, num2, num3= 100, 200, 300
print("{0:d} {1:5d} {2:05d}".format(num1, num2, num3))

name="정예린"
age=20
print(f"이름은 {name}이고, 나이는 {age}세이다.")

num1=num2=num3=10
sum=num1+num2+num3
print(f"{num1}+{num2}+{num3}의 합계는 {sum}이다.")

"""이스케이프 문자"""

print("안녕하세요, \n제 이름은 예린입니다.")

name="yerin"
age=20
city="seoul"
print(f"안녕하세요 {name} 입니다.")
print(f"제 나이는 {age}세이며,")
print("\t사는 곳은", city, "\b이고", "고향도 \""+city+"\"입니다.")

print("직사각형의 넓이=", 20*20)

가로=20
세로=20
넓이=가로*세로
print(f"직사각형의 넓이 = {넓이}")

"""**수행평가**"""

국어점수=100
영어점수=80
수학점수=75
총점=국어점수+영어점수+수학점수
평균=총점/3
print("[실행 결과]")
print(f"국어 : {국어점수}")
print(f"영어 : {영어점수}")
print(f"수학 : {수학점수}")
print(f"총점 : {총점}")
print("평균 : {0:0,.2f}".format(평균))