# -*- coding: utf-8 -*-
"""Week 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vt5-STi72mP3HLVJUeypY6MWcMi6sLCK

언어 설정 꼭 Phyton 3로
"""

print("Hello World!")

"""w 두번 쳐야됨!!"""

print("\\    /\\")
print(" )  ( ')")
print("(  /  )")
print(" \\(__)|")

name=input("이름을 입력하세요:")
age=input("나이를 입력하세요:")
print("당신의 이름은",name,"이고","나이는",age,"세 입니다.")

"""int"""

myage = input("당신의 나이를 입력하세요:")
fatherage=int(myage)+30
print("아버지의 나이는", fatherage, "입니다")

num1=int(input("숫자 정수1을 입력하세요:"))
num2=int(input("숫자 정수2를 입력하세요:"))
tot=num1+num2
print(f"{num1}과 {num2}의 합계는 {tot}이다.")

"""런타임 에러뜸"""

A=int(input("0보다 큰 숫자 정수1을 입력하세요:"))
B=int(input("10보다 작은 숫자 정수2를 입력하세요:"))
print(f"{A}+{B}")

"""map & split

-> .split(기준)
"""

a, b= map(int, input().split())
print(a+b)

a, b= map(int, input().split())
print(a-b)

name=input("이름을 입력하세요.:")
year,month,day=input("당신이 태어난 해의 년도, 월, 일을 차례로 입력하세요:").split()
print(f"{name}씨! 당신의 생년월일은 {year}년 {month}월 {day}일입니다.")

"""int() 주의

문자 숫자로 변환하기
"""

a=int(input("첫 번째 정수? "))
b=int(input("두 번째 정수? "))
c=int(input("세 번째 정수? "))
d=a+b+c
print("{0:,}과 {1:,}과 {2:,}의 합은 {3:,} 이다".format(a,b,c,d))

num1=int(input("첫 번째 정수? "))
num2=int(input("두 번째 정수? "))
num3=int(input("세 번째 정수? "))
hap=num1+num2+num3
print(f"{num1}과 {num2}과 {num3}의 합은 {hap:0,d} 이다")

"""6행 콤마 주의

7행 {0:0,.2f} 다음에 " 닫기
"""

국어=int(input("국어 : "))
영어=int(input("영어 : "))
수학=int(input("수학 : "))
총점=int(국어+수학+영어)
평균=int(총점/3)
print("총점 : ", 총점)
print("평균 : {0:0,.2f}".format(평균))

"""리스트 자료형 : 인덱스 [ ]"""

grade_list=[90,85,70,85,90]
print(grade_list[0])

"""추가 & 리스트 항목 삭제

-> .append .remove
"""

grade_list1=[]
grade_list1.append(100)
grade_list1.append(90)
grade_list1.append(80)
grade_list1.remove(80)
grade_list1

"""인덱스 삭제

-> del 리스트명[인덱스]
"""

num=[100,200,300,400,500]
del num[0]
print(num)
del num[-1]
num

"""특정 위치 값 삭제

-> 리스트명.pop(인덱스)
"""

num=[100,200,300,400,500]
num.pop(0)
print(num)

"""모든 항목 삭제 
-> 리스트명.clear()
"""

num=[100,200,300,400,500]
num.clear()
num

"""중간에 걍 리스트명 쓴다고 안띄워짐

맨 마지막에만 띄워지고 중간에 띄울라면 print로 해야됨
"""

list_color=["red", "blue", "orange", "green", "purple"]
list_color.pop(4)
print(list_color)
list_color.remove("orange")
print(list_color)
del list_color[0]
print(list_color)
del list_color[0]
print(list_color)
del list_color[0]
print(list_color)

((5*5)+2*((25-5)/5))**2

a=int(input("분자 값 : "))
b=int(input("분모 값 : "))
print("나눗셈 몫 =", a//b)
print("나눗셈 나머지 =", a%b)

화=int(input("화씨온도 : "))
섭=(화-32.0)/1.8
print("입력한 화씨온도", 화, "도는 섭씨온도로 {0:0,.2f}도 이다.".format(섭))

"""**수행평가**"""

용돈=int(input("부모님으로 부터 받은 용돈 : "))
거스름돈=용돈-3550
a=거스름돈//500
b=(거스름돈-(500*a))//100
c=(거스름돈-(500*a)-(100*b))//50
print("거스름돈 :", 거스름돈,"원")
print("500원 짜리 거스름돈 :",a,"개")
print("100원 짜리 거스름돈 :",b,"개")
print("50원 짜리 거스름돈 :",c,"개")